clair:
  database:
    type: pgsql
    options:
      cachesize: 16384
      source: postgres://clair:clair@quay-enterprise-clair-postgresql/clair?sslmode=disable
  updater:
    interval: 6h0m0s
  notifier:
    attempts: 1
    renotifyinterval: 1h0m0s
    http:
      endpoint: HTTPS://quay-enterprise-quay-quay-enterprise.apps.gbengaocp43.redhatgov.io/secscan/notify
      proxy: http://localhost:6063
  api:
    port: 6062
    healthport: 6061
    duration: 15m0s
    pagnationkey: XxoPtCUzrUv4JV5dS+yQ+MdW7yLEJnRMwigVY/bpgtQ=
jwtproxy:
  signer_proxy:
    enabled: true
    listen_addr: :6063
    ca_key_file: /certificates/mitm.key
    ca_crt_file: /certificates/mitm.crt
    signer:
      issuer: security_scanner
      expiration_time: 5m0s
      max_skew: 1m0s
      nonce_length: 32
      private_key:
        type: preshared
        options:
          key_id: 4d6fc290a58dc2fe076e62e13b87747fc19700222b7e33b1f0dca8b51d6366d8
          private_key_path: /clair/config/security_scanner.pem
  verifier_proxies:
  - enabled: true
    listen_addr: :6060
    crt_file: /clair/config/clair.crt
    key_file: /clair/config/clair.key
    verifier:
      upstream: http://localhost:6062
      audience: https://quay-enterprise-clair.quay-enterprise.svc:6060
      key_server:
        type: keyregistry
        options:
          registry: https://quay-enterprise-quay-quay-enterprise.apps.gbengaocp43.redhatgov.io/keys/