  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      quay-enterprise-component: clair-scanner
    name: quay-enterprise-clair
    namespace: quay-enterprise
  spec:
    replicas: 1
    selector:
      matchLabels:
        quay-enterprise-component: clair-scanner
    template:
      metadata:
        labels:
          quay-enterprise-component: clair-scanner
        namespace: quay-enterprise
      spec:
        containers:
        - image: quay.io/redhat/clair-jwt:v3.3.0
          imagePullPolicy: IfNotPresent
          name: clair-scanner
          ports:
          - containerPort: 6060
            name: clair-api
            protocol: TCP
          - containerPort: 6061
            name: clair-health
            protocol: TCP
          volumeMounts:
          - mountPath: /clair/config
            name: configvolume
          - mountPath: /etc/pki/ca-trust/source/anchors/quay.crt
            name: quay-ssl
            subPath: quay.crt
        imagePullSecrets:
        - name: redhat-quay-pull-secret
        restartPolicy: Always
        volumes:
        - name: configvolume
          projected:
            sources:        
              - secret:
                 items:
                   - key: security_scanner.pem
                     path: security_scanner.pem
                   - key: config.yaml
                     path: config.yaml
                   - key: tls.key
                     path: clair.key
                   - key: tls.crt
                     path: clair.crt      
                 name: clair-scanner-config-secret        
        - name: quay-ssl
          projected:
            sources:
              - secret:   
                  items:
                    - key: ssl.cert
                      path: quay.crt
                  name: quay-enterprise-config-secret
            defaultMode: 420